version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://bun.sh/install | bash
      - cp /root/.bun/bin/* /usr/local/bin
  build:
    commands:
      - bun install --frozen-lockfile
  post_build:
    commands:
      - echo 'Build finished'