version: 0.2

phases:
  install:
    commands:
      - RUN curl -fsSL https://bun.sh/install | bash
      - RUN cp /root/.bun/bin/* /usr/local/bin
      - bun install --frozen-lockfile
  post_build:
    commands:
      - bun start