name: check code quality

on:
  pull_request: # Run on pull requests
    branches:
      - main
  push: # Run on pushes to main
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run linters
        run: bun ci:lint
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: oven-sh/setup-bun@v1

  #     - name: Install dependencies
  #       run: bun install --frozen-lockfile
  #     - name: Run tests
  #       run: bun test